//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Time.java
//  @ Date : 20/10/2015
//  @ Author : 
//
//




/** */
public class Time
{
    /** */
    protected int second;
    
    /** */
    protected int minute;
    
    /** */
    protected int hour;
    
    /** */
    public Game Unnamed1;
    
    /** */
    public void Time()
    {
    
    }
    
    /** */
    public int getSecond()
    {
    
    }
    
    /** */
    public int getMinute()
    {
    
    }
    
    /** */
    public int getHour()
    {
    
    }
    
    /** */
    public void incrementTime()
    {
    
    }
}
